name: Publish Busybox image

on:
  push:
    tags:
      - busybox-*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.2.0

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Build and test Busybox Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./busybox/Dockerfile
          context: ./busybox
          target: test

      - name: Compute docker metadata
        id: meta
        run: |
          echo ::set-output name=BUILD_DATE::build_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo ::set-output name=VCS_REF::vcs_ref=$GITHUB_SHA
          echo ::set-output name=IMAGE_VERSION::image_version=${GITHUB_REF#refs/tags/}
          echo ::set-output name=TAGS::xfournet/jready:${GITHUB_REF#refs/tags/},xfournet/jready:busybox

      - name: Build and publish Busybox Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./busybox/Dockerfile
          context: ./busybox
          build-args: |
            ${{ steps.meta.outputs.BUILD_DATE }}
            ${{ steps.meta.outputs.VCS_REF }}
            ${{ steps.meta.outputs.IMAGE_VERSION }}
          push: true
          tags: ${{ steps.meta.outputs.TAGS }}
